name: furniture_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 
  flutter_slidable: ^3.1.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  date_format: ^2.0.7
  dotted_border: ^2.0.0+3
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  fluttertoast: ^8.2.1
  hexcolor: ^3.0.1
  flutter_colorpicker: ^1.0.3
  velocity_x: ^4.2.1
  group_button: ^5.2.2
  http: ^1.2.1
  loading_animation_widget: ^1.2.0+4
  pattern_formatter: ^4.0.0
  number_text_input_formatter: ^1.0.0+1
  colorful_background: ^0.0.4
  draggable_fab: ^0.1.4
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  jiffy: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icon/
    - assets/svg/
    - assets/category/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
